# Generated by Django 4.0 on 2021-12-18 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='please enter your own name', max_length=100)),
                ('last_name', models.CharField(help_text="please enter your father's name", max_length=100)),
            ],
        ),
    ]
